package com.county_cars.vroom.modules.attachment.storage;

import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;

/**
 * Storage abstraction for saving, loading and deleting files.
 *
 * <p>Switch between implementations via Spring profile:
 * <ul>
 *   <li>{@code spring.profiles.active=local} → LocalFileStorageService</li>
 *   <li>{@code spring.profiles.active=s3}    → S3FileStorageService</li>
 * </ul>
 * </p>
 */
public interface FileStorageService {

    /**
     * Persists the file and returns the relative storage path (or S3 object key).
     *
     * @param file            the uploaded multipart file
     * @param storedFileName  the UUID-based file name to use (generated by caller)
     * @param category        sub-folder / path prefix for organisation
     * @return the relative path used to later retrieve or delete the file
     */
    String store(MultipartFile file, String storedFileName, String category);

    /**
     * Loads a stored file as a Spring {@link Resource}.
     *
     * @param path the path returned by {@link #store}
     */
    Resource load(String path);

    /**
     * Permanently deletes the stored file.
     *
     * @param path the path returned by {@link #store}
     */
    void delete(String path);
}


